<a href="https://colab.research.google.com/github/justcating/pypairs/blob/main/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [10]:
b = np.arange(30, 70)

b[b % 2 == 0]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію np.linspace

In [9]:
np.linspace(0, 0.9, 10)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [4]:
def generate(matrix):
    n = matrix.shape[0]
    matrix_new = np.zeros((n+2, n+2), dtype=matrix.dtype)
    matrix_new[1: n+1, 1: n+1] = matrix
    return matrix_new


matrix = np.array([ [1,2],
                    [3,4]])

generate(matrix)

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [7]:
n = generate(matrix)
nFloat = n.astype('float32')

print(n.dtype)
print(nFloat.dtype)


int64
float32


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [12]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

In [15]:
x[x == var] = -1
x

array([ 1, -1,  3,  8,  6, -1,  7,  4])

In [17]:
x[x > var] = -1
x

array([ 1, -1,  3, -1, -1, -1, -1,  4])

In [18]:
x[x < var] = -1
x

array([-1, -1, -1, -1, -1, -1, -1, -1])

#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [21]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])



X[np.isnan(X)] = -1
X

array([[ 1.,  2., -1.,  4.],
       [ 5., -1., -1.,  4.],
       [-1., 10., 11., -1.]])

#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [29]:
array = np.random.randint(1, 10, (4,6))
array.reshape(3,8)

array([[4, 7, 5, 3, 1, 7, 8, 9],
       [6, 5, 6, 3, 7, 2, 7, 7],
       [5, 5, 2, 3, 4, 6, 9, 9]])

#Завдання 9
Створіть випадкову матрицю розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [35]:
arr = np.random.randint(1, 10, (3,4))

x1 = arr[:, 0]
x2 = arr[:, 1]
x3 = arr[:, 2]
x4 = arr[:, 3]

meanx1 = np.mean(x1)
meanx2 = np.mean(x2)
meanx3 = np.mean(x3)
meanx4 = np.mean(x4)
print(meanx1, meanx2, meanx3, meanx4)

5.666666666666667 6.0 4.0 5.666666666666667


#Завдання 10
Є матриця з ймовірностями того, що зображення(рядки) належить певному класу(стовпчики). Для кожного зображення(рядка) знайдіть індекс класу(стовпчика) з найбільшою ймовірністю

In [38]:
x = np.array([[0.2 , 0.3 , 0.23, 0.07, 0.03, 0.17],
              [0.15, 0.06, 0.21, 0.12, 0.24, 0.24],
              [0.1 , 0.21, 0.03, 0.07, 0.31, 0.28],
              [0.21, 0.24, 0.03, 0.18, 0.12, 0.21],
              [0.19, 0.25, 0.25, 0.06, 0.12, 0.12]])

np.argmax(x, axis=1)

array([1, 4, 4, 1, 1])

Пояснення: в першому рядку найбільша ймовірність -- 0.3 під індексом 1

в другому рядку -- 0.24 під індексом 4

в третьому рядку -- 0.31 під індексом 4

в четвертому рядку -- 0.24 під індексом 1

в п'ятому рядку -- 0.25 під індексом 1(там є ще одне 0.25, але ми беремо те що з меншим індексом)


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [40]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])


mask = np.logical_and(X > 3, X < 6)
X[mask]

array([4, 5, 5, 4])

#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [41]:
matrix = np.random.randint(0, 10, size=(5, 6))
matrix

array([[1, 4, 5, 6, 8, 6],
       [0, 5, 3, 5, 9, 6],
       [3, 1, 1, 6, 2, 1],
       [9, 5, 5, 7, 5, 2],
       [6, 1, 5, 6, 3, 0]])

In [49]:
min_val = matrix.min(axis=0)
max_val = matrix.max(axis=0)

matrix_normalized = (matrix - min_val) / (max_val - min_val)
matrix_normalized

array([[0.11111111, 0.75      , 1.        , 0.5       , 0.85714286,
        1.        ],
       [0.        , 1.        , 0.5       , 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.        , 0.5       , 0.        ,
        0.16666667],
       [1.        , 1.        , 1.        , 1.        , 0.42857143,
        0.33333333],
       [0.66666667, 0.        , 1.        , 0.5       , 0.14285714,
        0.        ]])